# Generated by Django 3.2 on 2021-04-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('Ini-cog', 'Engrenagem'), ('Ini-stats-up', 'Gráfico'), ('Ini-users', 'Usuários'), ('Ini-layers', 'Design'), ('Ini-mobile', 'Mobile'), ('Ini-rocket', 'Foguete')], max_length=20, verbose_name='Icone'),
        ),
    ]
